"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Award, BriefcaseBusiness, GraduationCap, Home, Plus, Trash2 } from "lucide-react";
import { AppShell, PageHeading } from "./app-shell"; import { EmptyState } from "./empty-state";
type AnyRow=Record<string,any>;
async function json(url:string,options?:RequestInit){const r=await fetch(url,options);if(r.status===401)throw new Error("Sign in to view and save your private history.");if(!r.ok)throw new Error("That change could not be saved.");return r.status===204?null:r.json();}
export function JourneyManager(){const [jobs,setJobs]=useState<AnyRow[]>([]),[homes,setHomes]=useState<AnyRow[]>([]),[credentials,setCredentials]=useState<AnyRow[]>([]),[tab,setTab]=useState("jobs"),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{try{const [j,h,c]=await Promise.all([json("/api/jobs"),json("/api/residences"),json("/api/credentials")]);setJobs(j.jobs);setHomes(h.residences);setCredentials(c.credentials)}catch(e){setNotice(e instanceof Error?e.message:"Unable to load history.")}},[]);useEffect(()=>{void load()},[load]);
 async function submit(event:FormEvent<HTMLFormElement>,url:string){event.preventDefault();setNotice("");const form=event.currentTarget;const raw=Object.fromEntries(new FormData(form));const body=url.includes("jobs")?{...raw,current:raw.current==="on",achievements:[],metadata:{}}:url.includes("credentials")?{...raw,details:{}}:raw;try{await json(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});form.reset();await load();setNotice("Saved. Your timeline is growing.")}catch(e){setNotice(e instanceof Error?e.message:"Save failed.")}}
 async function remove(url:string){try{await json(url,{method:"DELETE"});await load()}catch(e){setNotice(e instanceof Error?e.message:"Delete failed.")}}
 const tabs=[{id:"jobs",label:"Work",icon:BriefcaseBusiness},{id:"homes",label:"Residences",icon:Home},{id:"credentials",label:"Credentials",icon:Award}];
 return <AppShell><PageHeading eyebrow="Your journey" title="Every chapter counts." copy="Keep work, places, education, licenses, and certifications together—ready whenever an application asks."/><div className="mt-7 flex gap-2 overflow-auto">{tabs.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 rounded-full border-2 border-ink px-4 py-2 text-sm font-black ${tab===id?"bg-sun shadow-[0_3px_0_#26312c]":"bg-white"}`}><Icon size={17}/>{label}</button>)}</div>{notice&&<p role="status" className="mt-4 rounded-2xl bg-coral/15 px-4 py-3 text-sm font-bold">{notice}</p>}
 <section className="mt-6 grid gap-6 lg:grid-cols-[.75fr_1.25fr]">
  <div className="rounded-3xl border-2 border-ink bg-white p-5 shadow-[0_5px_0_#26312c]">{tab==="jobs"&&<form onSubmit={e=>submit(e,"/api/jobs")} className="space-y-3"><FormTitle icon={<BriefcaseBusiness/>} text="Add a work chapter"/><Input name="company" label="Company" required/><Input name="title" label="Title" required/><Input name="location" label="Location"/><div className="grid grid-cols-2 gap-3"><Input name="startedOn" label="Started" type="date"/><Input name="endedOn" label="Ended" type="date"/></div><label className="flex gap-2 text-sm font-bold"><input type="checkbox" name="current" className="accent-coral"/>I work here now</label><Submit/></form>}{tab==="homes"&&<form onSubmit={e=>submit(e,"/api/residences")} className="space-y-3"><FormTitle icon={<Home/>} text="Add a residence"/><Input name="label" label="Label" placeholder="First apartment" required/><Input name="street" label="Street" required/><div className="grid grid-cols-2 gap-3"><Input name="city" label="City" required/><Input name="region" label="State / region"/></div><div className="grid grid-cols-2 gap-3"><Input name="country" label="Country" required/><Input name="postalCode" label="Postal code"/></div><Submit/></form>}{tab==="credentials"&&<form onSubmit={e=>submit(e,"/api/credentials")} className="space-y-3"><FormTitle icon={<GraduationCap/>} text="Add a credential"/><label className="block text-xs font-black uppercase tracking-wider text-plum">Type<select name="kind" className="mt-1 w-full rounded-xl border-2 border-ink/15 px-3 py-2.5 text-sm normal-case"><option value="education">Education</option><option value="license">License</option><option value="certification">Certification</option></select></label><Input name="name" label="Name" required/><Input name="issuer" label="School or issuer"/><div className="grid grid-cols-2 gap-3"><Input name="issuedOn" label="Issued" type="date"/><Input name="expiresOn" label="Expires" type="date"/></div><Submit/></form>}</div>
  <div>{tab==="jobs"&&(jobs.length?<div className="space-y-3">{jobs.map(x=><Card key={x.id} icon={<BriefcaseBusiness/>} title={x.title} sub={`${x.company}${x.location?` · ${x.location}`:""}`} onDelete={()=>remove(`/api/jobs/${x.id}`)} pills={x.achievements}/>)}</div>:<EmptyState>Add your first role or use the AI Interviewer.</EmptyState>)}{tab==="homes"&&(homes.length?<div className="space-y-3">{homes.map(x=><Card key={x.id} icon={<Home/>} title={x.label} sub={[x.address?.street,x.address?.city,x.address?.region,x.address?.country].filter(Boolean).join(", ")} onDelete={()=>remove(`/api/residences/${x.id}`)}/>)}</div>:<EmptyState>Add a residence to make future forms painless.</EmptyState>)}{tab==="credentials"&&(credentials.length?<div className="space-y-3">{credentials.map(x=><Card key={x.id} icon={<Award/>} title={x.name} sub={`${x.kind} · ${x.issuer||"No issuer"}`} onDelete={()=>remove(`/api/credentials/${x.id}`)}/>)}</div>:<EmptyState>Add education, licenses, and certifications.</EmptyState>)}</div>
 </section></AppShell>}
function Input(p:{name:string;label:string;type?:string;required?:boolean;placeholder?:string}){return <label className="block text-xs font-black uppercase tracking-wider text-plum">{p.label}<input {...p} className="mt-1 w-full rounded-xl border-2 border-ink/15 px-3 py-2.5 text-sm font-bold normal-case outline-none focus:border-coral"/></label>}
function FormTitle({icon,text}:{icon:React.ReactNode;text:string}){return <h2 className="mb-4 flex items-center gap-2 font-[var(--font-display)] text-xl font-black">{icon}{text}</h2>}
function Submit(){return <button className="flex w-full items-center justify-center gap-2 rounded-2xl border-2 border-ink bg-coral py-3 font-black shadow-[0_4px_0_#26312c]"><Plus size={17}/>Save chapter</button>}
function Card({icon,title,sub,onDelete,pills=[]}:{icon:React.ReactNode;title:string;sub:string;onDelete:()=>void;pills?:string[]}){return <article className="rounded-3xl border-2 border-ink/15 bg-white/70 p-5"><div className="flex gap-4"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-mint/40">{icon}</div><div className="min-w-0 flex-1"><h3 className="font-[var(--font-display)] text-lg font-black">{title}</h3><p className="text-sm text-ink/55">{sub}</p>{pills.slice(0,3).map(x=><p key={x} className="mt-2 text-sm before:mr-2 before:text-coral before:content-['•']">{x}</p>)}</div><button onClick={onDelete} aria-label={`Delete ${title}`} className="self-start text-ink/30 hover:text-coral"><Trash2 size={18}/></button></div></article>}
