default_platform(:ios)

def api_key
  app_store_connect_api_key(
    key_id: ENV.fetch("APP_STORE_CONNECT_KEY_ID"),
    issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
    key_content: ENV.fetch("APP_STORE_CONNECT_KEY_BASE64"),
    is_key_content_base64: true
  )
end

platform :ios do
  before_all do
    sh("./bootstrap.sh")
  end

  lane :test do
    scan(
      project: "CareerGroove.xcodeproj",
      scheme: "CareerGroove",
      device: "iPhone 16 Pro",
      clean: true
    )
  end

  lane :beta do
    build_app(
      project: "CareerGroove.xcodeproj",
      scheme: "CareerGroove",
      export_method: "app-store",
      clean: true
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: false
    )
  end

  lane :release do
    build_app(
      project: "CareerGroove.xcodeproj",
      scheme: "CareerGroove",
      export_method: "app-store",
      clean: true
    )
    upload_to_app_store(
      api_key: api_key,
      force: true,
      submit_for_review: false,
      automatic_release: false
    )
  end
end
